project:
  type: website
  output-dir: docs

website:
  navbar:
    left:
      - text: "About"
        href: index.html
      # - text: "Publications" Link to cv section instead...
      #   href: publications
      - text: "Publications"
        href: cv/#publications
      - text: "CV"
        href: cv
      - text: "Presentations"
        href: presentations
      - text: "Blog"
        href: blog
      - text: "GitHub"
        href: https://github.com/maxlindmark
      - text: "Mastodon"
        href: https://ecoevo.social/@mlindmark
      - text: "Contact"
        href: contact
format:
  html:
    theme: Simplex
    fontsize: 1.2em
    image-width: 1.3em
    image-shape: round
    page-layout: full 
    css: styles.css
    toc: true
